apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genesis-cephfs-pvc
  namespace: genesis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem