apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: genesis
  namespace: genesis
spec:
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
  replicas: 3
  service:
    type: ClusterIP
  persistence:
    storageClassName: rook-ceph-fs
    storage: 20Gi

