apiVersion: apps/v1
kind: Deployment
metadata:
  name: genesis
  namespace: genesis
spec:
  selector:
    matchLabels:
      app: genesis
  template:
    metadata:
      labels:
        app: genesis
    spec:
      initContainers:
        - name: migrations
          image: koorinc/genesis:v0.0.9
          imagePullPolicy: IfNotPresent
          command: ['./migrate', 'migrate', 'up']
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_host
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_name
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_port
      containers:
        - name: genesis
          image: koorinc/genesis:v0.0.9
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_host
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_name
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_port
            - name: HETZNER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: hetzner_token
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: genesis-default-user
                  key: host
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: genesis-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: genesis-default-user
                  key: password
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: genesis-default-user
                  key: port
          volumeMounts:
            - name: main-store
              mountPath: /koor/
              readOnly: false
      volumes:
        - name: main-store
          persistentVolumeClaim:
            claimName: genesis-main-store
            readOnly: false
