apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genesis-main-store
  namespace: genesis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-fs
  volumeMode: Filesystem
