apiVersion: apps/v1
kind: Deployment
metadata:
  name: genesis-api
  namespace: genesis
spec:
  selector:
    matchLabels:
      app: genesis-api
  template:
    metadata:
      labels:
        app: genesis-api
    spec:
      containers:
        - name: genesis-api
          image: koorinc/genesis:v0.0.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_host
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_name
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_port
            - name: HETZNER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: hetzner_token