apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: genesis
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: javier@koor.tech
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx