apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: genesis
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: koorinc/genesis:v0.0.21
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
          - |
            if [ ! -f config.yaml ]; then
              /usr/local/bin/setup.sh
            fi;
            ./genesis monitor
          env:
            - name: GENESIS_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_host
            - name: GENESIS_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_user
            - name: GENESIS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_password
            - name: GENESIS_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_name
            - name: GENESIS_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: database_port
            - name: GENESIS_HETZNER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: hetzner_token
            - name: GENESIS_HCLOUD_TOKEN
              valueFrom:
                 secretKeyRef:
                   name: genesis-api
                   key: hetzner_token
            - name: GENESIS_RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: genesis-api
                  key: rabbitmq_host
            - name: GENESIS_RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: genesis-default-user
                  key: username
            - name: GENESIS_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: genesis-default-user
                  key: password
            - name: GENESIS_RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: genesis-default-user
                  key: port
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: main-store
              mountPath: /koor/
              readOnly: false

      volumes:
        - name: main-store
          persistentVolumeClaim:
            claimName: genesis-main-store
            readOnly: false
